name: build
on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  push:
    branches:
      - 'main'       # Run the workflow when pushing to the main branch
  pull_request:
    branches:
      - '*'          # Run the workflow for all pull requests
  release:
    types:
      - published    # Run the workflow when a new GitHub release is published

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget
  
defaults:
  run:
    shell: pwsh
 
jobs:
  create_nuget:
    runs-on: ubuntu-latest
    steps:
      - name: Detect version
        id: get_version
        run: |
          $SEMVER="${{ startsWith(github.ref, 'refs/tags/v') && github.ref_name || '' }}".ToLower().Replace("v", "")
          echo "VERSION=$SEMVER"
          echo "VERSION=$SEMVER" >> $env:GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: 'nuget'
          sparse-checkout-cone-mode: false
            
      # This step is needed because we can't check out a subdirectory.
      # Therefore, all `nuget/` files should be moved to the project root.
      - name: Move `nuget` files to root
        run: |
          Get-ChildItem -Force | Select-Object Mode, LastWriteTime, Length, Name | Format-Table -AutoSize
          Get-ChildItem -Path "nuget" -Force | Move-Item -Destination "."
          Remove-Item -Recurse -Force -Path "nuget"
          Get-ChildItem -Force | Select-Object Mode, LastWriteTime, Length, Name | Format-Table -AutoSize

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - run: echo '${{ toJSON(steps.get_version.outputs) }}'

      - run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }} /p:Version="${{ steps.get_version.outputs.VERSION != '' && steps.get_version.outputs.VERSION || format('1.0.{0}', github.run_number) }}"

      - uses: actions/upload-artifact@v4
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 7
          path: ${{ env.NuGetDirectory }}/*.nupkg
          
          
  deploy:
    # Publish only when creating a GitHub Release
    # https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
    # You can update this logic if you want to manage releases differently
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: [ create_nuget ]
    steps:
      # Download the NuGet package created in the previous job
      - uses: actions/download-artifact@v4
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}
      
      # Install the .NET SDK indicated in the global.json file
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
      
      # TODO: Enable this step!
      # Publish all NuGet packages to NuGet.org
      # Use --skip-duplicate to prevent errors if a package with the same version already exists.
      # If you retry a failed workflow, already published packages will be skipped without error.
#      - name: Publish NuGet package
#        run: |
#          foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
#              dotnet nuget push $file --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
#          }